// <auto-generated />
using System;
using CadernetaObras.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CadernetaObras.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815200506_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CadernetaObras.Domain.Entities.AssinaturaObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("ObraId")
                        .HasColumnType("integer");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObraId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("assinaturas_obra", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.AssinaturaRelato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RelatoVisitaId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatoVisitaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("assinaturas_relato", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.AssinaturaTermoConclusao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TermoConclusaoId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TermoConclusaoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("assinaturas_termo_conclusao", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RelatoVisitaId")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RelatoVisitaId");

                    b.ToTable("imagens", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaAmpliarM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AreaConstruirM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AreaReformarM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AreaRegularizarM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AreaTotalEdificadaM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("AtivTecnicaDirecao")
                        .HasColumnType("boolean");

                    b.Property<bool>("AtivTecnicaExecucao")
                        .HasColumnType("boolean");

                    b.Property<bool>("AtivTecnicaFiscalizacao")
                        .HasColumnType("boolean");

                    b.Property<bool>("AtivTecnicaProjeto")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CnpjEmpresa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("DataReciboAbertura")
                        .HasColumnType("date");

                    b.Property<Guid>("IdAdministrador")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProfissional")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProprietario")
                        .HasColumnType("uuid");

                    b.Property<string>("LocalObra")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeEmpresa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumeroCaderneta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroRt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoEdificacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoEdificacaoOutros")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("ValorObra")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroCaderneta")
                        .IsUnique();

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.RelatoVisita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataVisita")
                        .HasColumnType("date");

                    b.Property<string>("DecisoesOrientacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FaseAlvenarias")
                        .HasColumnType("boolean");

                    b.Property<bool>("FaseCobertura")
                        .HasColumnType("boolean");

                    b.Property<bool>("FaseEsquadriasInst")
                        .HasColumnType("boolean");

                    b.Property<bool>("FaseFundacao")
                        .HasColumnType("boolean");

                    b.Property<bool>("FasePintura")
                        .HasColumnType("boolean");

                    b.Property<bool>("FaseRevestimento")
                        .HasColumnType("boolean");

                    b.Property<bool>("FaseServicosComp")
                        .HasColumnType("boolean");

                    b.Property<bool>("FaseServicosPreliminares")
                        .HasColumnType("boolean");

                    b.Property<bool>("FaseSuperestrutura")
                        .HasColumnType("boolean");

                    b.Property<int>("ObraId")
                        .HasColumnType("integer");

                    b.Property<string>("PosicaoObra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("relatos_visita", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.TermoConclusao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<string>("Declaracao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObraId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId")
                        .IsUnique();

                    b.ToTable("termos_conclusao", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NumeroRegistro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TituloProfissional")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.AssinaturaObra", b =>
                {
                    b.HasOne("CadernetaObras.Domain.Entities.Obra", "Obra")
                        .WithMany("Assinaturas")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.AssinaturaRelato", b =>
                {
                    b.HasOne("CadernetaObras.Domain.Entities.RelatoVisita", "RelatoVisita")
                        .WithMany("Assinaturas")
                        .HasForeignKey("RelatoVisitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatoVisita");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.AssinaturaTermoConclusao", b =>
                {
                    b.HasOne("CadernetaObras.Domain.Entities.TermoConclusao", "TermoConclusao")
                        .WithMany("Assinaturas")
                        .HasForeignKey("TermoConclusaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TermoConclusao");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.Imagem", b =>
                {
                    b.HasOne("CadernetaObras.Domain.Entities.RelatoVisita", "RelatoVisita")
                        .WithMany("Imagens")
                        .HasForeignKey("RelatoVisitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatoVisita");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.RelatoVisita", b =>
                {
                    b.HasOne("CadernetaObras.Domain.Entities.Obra", "Obra")
                        .WithMany("RelatosVisita")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.TermoConclusao", b =>
                {
                    b.HasOne("CadernetaObras.Domain.Entities.Obra", "Obra")
                        .WithOne("TermoConclusao")
                        .HasForeignKey("CadernetaObras.Domain.Entities.TermoConclusao", "ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.Obra", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("RelatosVisita");

                    b.Navigation("TermoConclusao");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.RelatoVisita", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("CadernetaObras.Domain.Entities.TermoConclusao", b =>
                {
                    b.Navigation("Assinaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
